# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Headers.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents are derived from the file locations

set( INCLUDE_DIRS
src/reflect
src/generic
src/array
src/array/pointer
src/array/struct
src/assoc
src/assoc/pointerpair
src/map
src/map/pointer
src
src/queue
src/queue/struct
src/rangeset
src/set
src/set/pointer
)

#
# contents selected with patternfile ??-header--private-generated-headers
#
set( PRIVATE_GENERATED_HEADERS
src/reflect/_mulle-container-debug-include-private.h
)

#
# contents selected with patternfile ??-header--private-generic-headers
#
set( PRIVATE_GENERIC_HEADERS
src/generic/include-private.h
)

#
# contents selected with patternfile ??-header--public-generated-headers
#
set( PUBLIC_GENERATED_HEADERS
src/reflect/_mulle-container-debug-include.h
src/reflect/_mulle-container-debug-provide.h
)

#
# contents selected with patternfile ??-header--public-generic-headers
#
set( PUBLIC_GENERIC_HEADERS
src/generic/include.h
)

#
# contents selected with patternfile ??-header--public-headers
#
set( PUBLIC_HEADERS
src/array/mulle--array-debug.h
src/array/mulle-array-debug.h
src/array/mulle-flexarray-debug.h
src/array/pointer/mulle--pointerarray-debug.h
src/array/pointer/mulle-pointerarray-debug.h
src/array/struct/mulle--structarray-debug.h
src/array/struct/mulle-structarray-debug.h
src/assoc/mulle--assoc-debug.h
src/assoc/mulle-assoc-debug.h
src/assoc/pointerpair/mulle--pointerpairarray-debug.h
src/assoc/pointerpair/mulle-pointerpairarray-debug.h
src/assoc/pointerpair/mulle-pointerpair-debug.h
src/map/mulle--map-debug.h
src/map/mulle-map-debug.h
src/map/pointer/mulle--pointermap-debug.h
src/map/pointer/mulle--pointermap-generic-debug.h
src/map/pointer/mulle--pointermap-struct-debug.h
src/mulle-container-debug.h
src/queue/mulle--pointerqueue-debug.h
src/queue/mulle-pointerqueue-debug.h
src/queue/struct/mulle--structqueue-debug.h
src/queue/struct/mulle-structqueue-debug.h
src/rangeset/mulle--rangeset-debug.h
src/set/mulle--set-debug.h
src/set/mulle-set-debug.h
src/set/pointer/mulle--pointerset-debug.h
src/set/pointer/mulle-pointerset-debug.h
src/set/pointer/mulle--pointerset-generic-debug.h
src/set/pointer/mulle--pointerset-struct-debug.h
)

