# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/array/mulle--array-debug.c
src/array/mulle-array-debug.c
src/array/pointer/mulle--pointerarray-debug.c
src/array/struct/mulle--structarray-debug.c
src/array/struct/mulle-structarray-debug.c
src/assoc/mulle--assoc-debug.c
src/assoc/mulle-assoc-debug.c
src/assoc/pointerpair/mulle--pointerpairarray-debug.c
src/assoc/pointerpair/mulle-pointerpairarray-debug.c
src/assoc/pointerpair/mulle-pointerpair-debug.c
src/map/mulle--map-debug.c
src/map/mulle-map-debug.c
src/map/pointer/mulle--pointermap-generic-debug.c
src/map/pointer/mulle--pointermap-struct-debug.c
src/mulle-container-debug.c
src/queue/mulle--pointerqueue-debug.c
src/queue/mulle-pointerqueue-debug.c
src/queue/struct/mulle--structqueue-debug.c
src/queue/struct/mulle-structqueue-debug.c
src/rangeset/mulle--rangeset-debug.c
src/set/mulle--set-debug.c
src/set/mulle-set-debug.c
src/set/pointer/mulle-pointerset-debug.c
src/set/pointer/mulle--pointerset-generic-debug.c
src/set/pointer/mulle--pointerset-struct-debug.c
)
